In [39]:
import numpy as np
import pandas as pd

In [40]:
data = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [41]:
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [42]:
df = data.copy()

In [43]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [44]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [45]:
df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [46]:
df.drop('id',axis=1,inplace=True)

In [47]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

In [48]:
df.describe

<bound method NDFrame.describe of       gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private
1     Female  61.0             0              0          Yes  Self-employed
2       Male  80.0             0              1          Yes        Private
3     Female  49.0             0              0          Yes        Private
4     Female  79.0             1              0          Yes  Self-employed
...      ...   ...           ...            ...          ...            ...
5105  Female  80.0             1              0          Yes        Private
5106  Female  81.0             0              0          Yes  Self-employed
5107  Female  35.0             0              0          Yes  Self-employed
5108    Male  51.0             0              0          Yes        Private
5109  Female  44.0             0              0          Yes       Govt_job

     Residence_type  avg_glucose_level        bmi   smoking_status  stroke
0             Urban             228.69  36.600000  formerly smoked       1
1             Rural             202.21  28.893237     never smoked       1
2             Rural             105.92  32.500000     never smoked       1
3             Urban             171.23  34.400000           smokes       1
4             Rural             174.12  24.000000     never smoked       1
...             ...                ...        ...              ...     ...
5105          Urban              83.75  28.893237     never smoked       0
5106          Urban             125.20  40.000000     never smoked       0
5107          Rural              82.99  30.600000     never smoked       0
5108          Rural             166.29  25.600000  formerly smoked       0
5109          Urban              85.28  26.200000          Unknown       0

[5110 rows x 11 columns]>

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             5110 non-null   object
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   ever_married       5110 non-null   object
 5   work_type          5110 non-null   object
 6   Residence_type     5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df.drop_duplicates()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

In [52]:
df.shape

(5110, 11)

In [53]:
df.duplicated(subset=["bmi"]).sum()

np.int64(4691)

In [54]:
df[['bmi', 'age']].isnull().sum()

bmi    0
age    0
dtype: int64

In [55]:
df['stroke'].value_counts()
# // ie data is imbalanced

stroke
0    4861
1     249
Name: count, dtype: int64

In [56]:
df['age'].value_counts()
#  most of age is at 78 and greater than 50

age
78.00    102
57.00     95
52.00     90
54.00     87
51.00     86
        ...
1.40       3
0.48       3
0.16       3
0.08       2
0.40       2
Name: count, Length: 104, dtype: int64

In [57]:
df.iloc[0:5,:]

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1

In [58]:
df.loc[df['age'] > 50]
# almost half of data is has age greater than age 50

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.000000,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5100,Male,82.0,1,0,Yes,Self-employed,Rural,71.97,28.300000,never smoked,0
5102,Female,57.0,0,0,Yes,Private,Rural,77.93,21.700000,never smoked,0
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0

In [59]:
df[df['stroke'] == 1]
df[(df['age'] > 60) & (df['hypertension'] == 1)]

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
6,Male,74.0,1,1,Yes,Private,Rural,70.09,27.400000,never smoked,1
10,Female,81.0,1,0,Yes,Private,Rural,80.43,29.700000,never smoked,1
17,Male,75.0,1,0,Yes,Private,Urban,221.29,25.800000,smokes,1
32,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.200000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
4983,Male,76.0,1,0,Yes,Private,Rural,267.60,30.500000,never smoked,0
4987,Male,64.0,1,0,Yes,Private,Rural,196.26,34.500000,Unknown,0
5088,Female,64.0,1,0,Yes,Self-employed,Urban,76.89,30.200000,Unknown,0
5100,Male,82.0,1,0,Yes,Self-employed,Rural,71.97,28.300000,never smoked,0
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             5110 non-null   object
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   ever_married       5110 non-null   object
 5   work_type          5110 non-null   object
 6   Residence_type     5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB

In [61]:
df['age'] =  df['age'].astype(int)

In [62]:
df['hypertension'] = df['hypertension'].astype(int)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             5110 non-null   object
 1   age                5110 non-null   int64
 2   hypertension       5110 non-null   int64
 3   heart_disease      5110 non-null   int64
 4   ever_married       5110 non-null   object
 5   work_type          5110 non-null   object
 6   Residence_type     5110 non-null   object
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                5110 non-null   float64
 9   smoking_status     5110 non-null   object
 10  stroke             5110 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 439.3+ KB

In [64]:
df['gender'].replace({'Male': 1, 'Female': 0}, inplace=True)

C:\Users\omkar\AppData\Local\Temp\ipykernel_35396\2830719696.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].replace({'Male': 1, 'Female': 0}, inplace=True)

In [65]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,1,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,0,61,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,1,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,0,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,0,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,0,80,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,0,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,0,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,1,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,0,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

In [66]:
df['gender'].dtype

dtype('O')

In [67]:
df['gender'].unique()

array([1, 0, 'Other'], dtype=object)

In [68]:
df['gender'] = df['gender'].astype(str)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])

In [69]:
df['gender'].dtype

dtype('int64')

In [70]:
df['age'].mean()

np.float64(43.21526418786693)

In [71]:

df['avg_glucose_level'].min()

55.12

In [72]:
df['bmi'].median()

28.4

In [73]:
df['avg_glucose_level'].max()

271.74

In [74]:
df.groupby('stroke')['age'].mean()
# more chance of strokr in male

stroke
0    41.959679
1    67.726908
Name: age, dtype: float64

In [75]:
df.groupby('gender')['bmi'].mean()
# the order of bmi is : 0 > 1 > 2

gender
0    29.060168
1    28.659998
2    22.400000
Name: bmi, dtype: float64

In [76]:
df.sort_values(by='age' , ascending = False)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
1042,0,82,0,0,No,Self-employed,Urban,82.21,26.0,never smoked,0
3108,1,82,0,0,No,Self-employed,Urban,161.95,30.8,never smoked,0
5062,0,82,0,0,Yes,Self-employed,Rural,211.58,36.9,never smoked,0
35,0,82,1,1,No,Private,Rural,84.03,26.5,formerly smoked,1
1029,1,82,0,0,Yes,Self-employed,Rural,85.29,27.0,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...
2358,1,0,0,0,No,children,Urban,112.19,18.9,Unknown,0
4293,1,0,0,0,No,children,Urban,57.09,19.4,Unknown,0
1614,0,0,0,0,No,children,Urban,139.67,14.1,Unknown,0
4409,0,0,0,0,No,children,Rural,112.19,20.1,Unknown,0
5089,0,0,0,0,No,children,Rural,62.13,16.8,Unknown,0

In [77]:
df['age'].tail()

5105    80
5106    81
5107    35
5108    51
5109    44
Name: age, dtype: int64

In [78]:
df.rename(columns={'avg_glucose_level' : 'glucose'} , inplace =True)

In [79]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,glucose,bmi,smoking_status,stroke
0,1,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,0,61,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,1,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,0,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,0,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,0,80,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,0,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,0,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,1,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,0,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

In [80]:
df['bmi'].describe()

count    5110.000000
mean       28.893237
std         7.698018
min        10.300000
25%        23.800000
50%        28.400000
75%        32.800000
max        97.600000
Name: bmi, dtype: float64

In [81]:
df['work_type'].nunique()

5

In [82]:
(df['age'] < 0).sum()

np.int64(0)

In [83]:
cleanD = df.copy()

In [84]:
cleanD

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,glucose,bmi,smoking_status,stroke
0,1,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked,1
1,0,61,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked,1
2,1,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked,1
3,0,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes,1
4,0,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5105,0,80,1,0,Yes,Private,Urban,83.75,28.893237,never smoked,0
5106,0,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked,0
5107,0,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked,0
5108,1,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked,0
5109,0,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown,0

In [85]:
X = cleanD.drop('stroke', axis=1)
y = cleanD['stroke']

In [86]:
X.values

array([[1, 67, 0, ..., 228.69, 36.6, 'formerly smoked'],
       [0, 61, 0, ..., 202.21, 28.893236911794666, 'never smoked'],
       [1, 80, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       [0, 35, 0, ..., 82.99, 30.6, 'never smoked'],
       [1, 51, 0, ..., 166.29, 25.6, 'formerly smoked'],
       [0, 44, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [87]:
y.values

array([1, 1, 1, ..., 0, 0, 0])

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y   
)

In [89]:
y.value_counts(normalize=True)

stroke
0    0.951272
1    0.048728
Name: proportion, dtype: float64

In [90]:
y_train.value_counts(normalize=True)

stroke
0    0.951321
1    0.048679
Name: proportion, dtype: float64

In [91]:
y_test.value_counts(normalize=True)

stroke
0    0.951076
1    0.048924
Name: proportion, dtype: float64

In [92]:
X

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,glucose,bmi,smoking_status
0,1,67,0,1,Yes,Private,Urban,228.69,36.600000,formerly smoked
1,0,61,0,0,Yes,Self-employed,Rural,202.21,28.893237,never smoked
2,1,80,0,1,Yes,Private,Rural,105.92,32.500000,never smoked
3,0,49,0,0,Yes,Private,Urban,171.23,34.400000,smokes
4,0,79,1,0,Yes,Self-employed,Rural,174.12,24.000000,never smoked
...,...,...,...,...,...,...,...,...,...,...
5105,0,80,1,0,Yes,Private,Urban,83.75,28.893237,never smoked
5106,0,81,0,0,Yes,Self-employed,Urban,125.20,40.000000,never smoked
5107,0,35,0,0,Yes,Self-employed,Rural,82.99,30.600000,never smoked
5108,1,51,0,0,Yes,Private,Rural,166.29,25.600000,formerly smoked
5109,0,44,0,0,Yes,Govt_job,Urban,85.28,26.200000,Unknown

In [93]:
y

0       1
1       1
2       1
3       1
4       1
       ..
5105    0
5106    0
5107    0
5108    0
5109    0
Name: stroke, Length: 5110, dtype: int64

In [94]:
X_train

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,glucose,bmi,smoking_status
845,0,48,0,0,Yes,Private,Urban,69.21,33.1,never smoked
3744,1,15,0,0,No,Private,Rural,122.25,21.0,never smoked
4183,0,67,0,0,Yes,Self-employed,Rural,110.42,24.9,never smoked
3409,1,44,0,0,Yes,Private,Urban,65.41,24.8,smokes
284,1,14,0,0,No,Govt_job,Urban,82.34,31.6,Unknown
...,...,...,...,...,...,...,...,...,...,...
1434,0,45,0,0,Yes,Private,Urban,92.86,35.1,formerly smoked
461,0,16,0,0,No,children,Rural,113.47,19.5,Unknown
1052,0,61,0,0,Yes,Private,Rural,78.65,36.2,formerly smoked
1757,1,31,0,0,Yes,Private,Urban,74.05,26.0,Unknown
5052,0,6,0,0,No,children,Urban,91.05,22.1,Unknown

In [95]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['ever_married', 'work_type', 'Residence_type', 'smoking_status']

for col in categorical_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col].astype(str))
    X_test[col] = le.transform(X_test[col].astype(str))

In [96]:
X_train

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,glucose,bmi,smoking_status
845,0,48,0,0,1,2,1,69.21,33.1,2
3744,1,15,0,0,0,2,0,122.25,21.0,2
4183,0,67,0,0,1,3,0,110.42,24.9,2
3409,1,44,0,0,1,2,1,65.41,24.8,3
284,1,14,0,0,0,0,1,82.34,31.6,0
...,...,...,...,...,...,...,...,...,...,...
1434,0,45,0,0,1,2,1,92.86,35.1,1
461,0,16,0,0,0,4,0,113.47,19.5,0
1052,0,61,0,0,1,2,0,78.65,36.2,1
1757,1,31,0,0,1,2,1,74.05,26.0,0
5052,0,6,0,0,0,4,1,91.05,22.1,0

In [97]:
X_train['work_type'].value_counts()

work_type
2    2332
3     667
4     554
0     522
1      13
Name: count, dtype: int64

In [98]:
X_train['Residence_type'].value_counts()

Residence_type
1    2069
0    2019
Name: count, dtype: int64

In [99]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)  # fit ONLY on training data
X_test  = scaler.transform(X_test)       # apply same scaling to test data

In [100]:
X_train

array([[-0.84034436,  0.20598133, -0.32796178, ..., -0.8199733 ,
         0.53847936,  0.58922535],
       [ 1.18759409, -1.25315045, -0.32796178, ...,  0.35207477,
        -1.02064076,  0.58922535],
       [-0.84034436,  1.04608751, -0.32796178, ...,  0.09066209,
        -0.51811444,  0.58922535],
       ...,
       [-0.84034436,  0.78079082, -0.32796178, ..., -0.61137349,
         0.93792335, -0.34367675],
       [ 1.18759409, -0.54569262, -0.32796178, ..., -0.71302171,
        -0.37637625, -1.27657885],
       [-0.84034436, -1.65109549, -0.32796178, ..., -0.33736527,
        -0.87890256, -1.27657885]])

In [101]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

import pickle

In [102]:
lr = LogisticRegression(class_weight='balanced', max_iter=1000)
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

In [103]:
lr_pred

array([1, 0, 0, ..., 0, 0, 0])

In [104]:
dt = DecisionTreeClassifier(class_weight='balanced', random_state=42)
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

In [105]:
dt_pred

array([0, 0, 0, ..., 0, 0, 0])

In [106]:
rf = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42
)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

In [107]:
rf_pred

array([0, 0, 0, ..., 0, 0, 0])

In [108]:
def evaluate(name, y_true, y_pred):
    print(f"\n{name}")
    print("Accuracy :", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred))
    print("Recall   :", recall_score(y_true, y_pred))
    print("F1-score :", f1_score(y_true, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))


evaluate("Logistic Regression", y_test, lr_pred)
evaluate("Decision Tree", y_test, dt_pred)
evaluate("Random Forest", y_test, rf_pred)

Logistic Regression
Accuracy : 0.7524461839530333
Precision: 0.1413427561837456
Recall   : 0.8
F1-score : 0.24024024024024024
Confusion Matrix:
 [[729 243]
 [ 10  40]]

Decision Tree
Accuracy : 0.9178082191780822
Precision: 0.11363636363636363
Recall   : 0.1
F1-score : 0.10638297872340426
Confusion Matrix:
 [[933  39]
 [ 45   5]]

Random Forest
Accuracy : 0.9500978473581213
Precision: 0.0
Recall   : 0.0
F1-score : 0.0
Confusion Matrix:
 [[971   1]
 [ 50   0]]

In [109]:
pickle.dump(rf, open("model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

In [110]:
y_test

3725    0
4481    0
1545    0
1820    0
1262    0
       ..
1042    0
1171    0
3199    0
3208    0
1819    0
Name: stroke, Length: 1022, dtype: int64

In [111]:
X_train

array([[-0.84034436,  0.20598133, -0.32796178, ..., -0.8199733 ,
         0.53847936,  0.58922535],
       [ 1.18759409, -1.25315045, -0.32796178, ...,  0.35207477,
        -1.02064076,  0.58922535],
       [-0.84034436,  1.04608751, -0.32796178, ...,  0.09066209,
        -0.51811444,  0.58922535],
       ...,
       [-0.84034436,  0.78079082, -0.32796178, ..., -0.61137349,
         0.93792335, -0.34367675],
       [ 1.18759409, -0.54569262, -0.32796178, ..., -0.71302171,
        -0.37637625, -1.27657885],
       [-0.84034436, -1.65109549, -0.32796178, ..., -0.33736527,
        -0.87890256, -1.27657885]])

In [112]:
X_test

array([[ 1.18759409,  0.86922305, -0.32796178, ..., -0.62065442,
         0.75752929,  0.58922535],
       [-0.84034436, -0.01509924, -0.32796178, ..., -0.43415205,
         0.56424994,  0.58922535],
       [-0.84034436, -0.89942154, -0.32796178, ...,  0.44974544,
        -0.02847341,  1.52212745],
       ...,
       [-0.84034436,  0.29441356, -0.32796178, ..., -0.31305809,
        -1.04641134,  0.58922535],
       [ 1.18759409, -1.25315045, -0.32796178, ..., -0.96670029,
         0.43539704,  0.58922535],
       [-0.84034436,  0.33862968, -0.32796178, ..., -0.50862041,
         0.65444697, -0.34367675]])

In [113]:
y_train

845     0
3744    0
4183    0
3409    0
284     0
       ..
1434    0
461     0
1052    0
1757    0
5052    0
Name: stroke, Length: 4088, dtype: int64

In [114]:
y_test

3725    0
4481    0
1545    0
1820    0
1262    0
       ..
1042    0
1171    0
3199    0
3208    0
1819    0
Name: stroke, Length: 1022, dtype: int64